//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDONH
    {
        public string SODH { get; set; }
        public string MAVTU { get; set; }
        public Nullable<int> SLDAT { get; set; }
    
        public virtual DONDH DONDH { get; set; }
        public virtual VATTU VATTU { get; set; }
    }
}
