//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPNHAP
    {
        public string SOPN { get; set; }
        public string MAVTU { get; set; }
        public Nullable<int> SLNHAP { get; set; }
        public Nullable<decimal> DGNHAP { get; set; }
    
        public virtual PNHAP PNHAP { get; set; }
        public virtual VATTU VATTU { get; set; }
    }
}
