//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPXUAT
    {
        public string SOPX { get; set; }
        public string MAVTU { get; set; }
        public Nullable<int> SLXUAT { get; set; }
        public Nullable<decimal> DGXUAT { get; set; }
    
        public virtual PXUAT PXUAT { get; set; }
        public virtual VATTU VATTU { get; set; }
    }
}
