//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTHU
    {
        public string SOCT { get; set; }
        public string NGAYCT { get; set; }
        public Nullable<decimal> SOTIEN { get; set; }
        public string DIENGIAI { get; set; }
        public string SOPX { get; set; }
    }
}
