//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class PXUAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PXUAT()
        {
            this.CTPXUAT = new HashSet<CTPXUAT>();
        }
    
        public string SOPX { get; set; }
        public Nullable<System.DateTime> NGAYXUAT { get; set; }
        public string TENKH { get; set; }
        public string NHANVIEN { get; set; }
        public Nullable<int> TIENHANG { get; set; }
        public Nullable<int> DATRA { get; set; }
        public Nullable<int> CONNO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPXUAT> CTPXUAT { get; set; }
    }
}
