//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class TONKHO
    {
        public string NAMTHANG { get; set; }
        public string MAVTU { get; set; }
        public Nullable<int> SLDAU { get; set; }
        public Nullable<int> TONGSLNHAP { get; set; }
        public Nullable<int> TONGSLXUAT { get; set; }
        public Nullable<int> SLCUOI { get; set; }
    
        public virtual VATTU VATTU { get; set; }
    }
}
